<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PekerjaanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            'PETANI/PEKEBUN',
            'PETERNAK',
            'NELAYAN/PERIKANAN',
            'TRANSPORTASI',
            'BURUH TANI/PERKEBUNAN',
            'BURUH NELAYAN/PERIKANAN',
            'BURUH PETERNAK',
            'PEKERJA RUMAH TANGGA',
            'TUKANG CUKUR',
            'TUKANG LISTRIK',
            'TUKANG BATU',
            'TUKANG KAYU',
            'TUKANG SOL SEPATU',
            'TUKANG LAS/PANDAI BESI',
            'TUKANG JAHIT',
            'TUKANG GIGI',
            'PENATA RIAS',
            'PENATA BUSANA',
            'PENATA RAMBUT',
            'MEKANIK',
            'SENIMAN',
            'TABIB',
            'PARAJI',
            'PERANCANG BUSANA',
            'PENTERJEMAH',
            'IMAM MESJID',
            'PENDETA',
            'PASTOR',
            'WARTAWAN',
            'USTADZ/MUBALIGH',
            'JURU MASAK',
            'PROMOTOR ACARA',
            'DOSEN',
            'GURU',
            'PENGACARA',
            'NOTARIS',
            'ARSITEK',
            'KONSULTAN',
            'DOKTER',
            'BIDAN',
            'APOTEKER',
            'PSIKIATER/PSIKOLOG',
            'PENYIAR RADIO',
            'PELAUT',
            'PENELITI',
            'SOPIR',
            'PIALANG',
            'PARANORMAL',
            'PEDAGANG',
            'BIARAWATI',
            'DRIVER GOJEK',
            'DRIVER GRAB',
            'MITRA UBER',
            'PESERTA MAGANG',
            'SISWA KERJA PRAKTEK',
            'TENAGA HONORER (SELAIN PENYELENGGARA NEGARA)',
            'NARAPIDANA DALAM PROSES ASIMILASI',
            'ATLET',
            'ARTIS',
            'JURU PARKIR',
            'TUKANG PIJAT',
            'PEMANDU LAGU',
            'PENDAMPING DESA',
            'BURUH BONGKAR MUAT/BAGASI',
            'RELAWAN TAGANA/RELAWAN BENCANA',
            'TUKANG SAMPAH',
            'PEMULUNG',
            'MARBOT MESJID',
            'MITRA GOJEK-GO LIFE',
            'PESERTA BAKAT DAN MINAT',
            'AHLI GIZI',
            'DOKTER GIGI',
            'FISIKAWAN MEDIK',
            'PERAWAT',
            'PEREKAM MEDIK DAN INFOKES',
            'PSIKOLOGI KLINIS',
            'RADIOGRAFER',
            'TEKNISI LAB MEDIK',
            'TENAGA KESEHATAN LINGKUNGAN',
            'TENAGA TEKNIS KEFARMASIAN',
            'ADMINISTRASI',
            'SEKRETARIS',
            'LOGISTIK',
            'PETUGAS KEAMANAN',
            'PEMASAR IKAN',
            'PEMASAR PELABUHAN',
            'PENGOLAH IKAN',
            'PEMBUDIDAYA IKAN',
            'PETAMBAK GARAM',
            'AGEN16',
            'MITRA TELEPORT AIRASIA',
            'PERISAI',
            'MITRA SHOPEE',
            'AGEN BRILINK',
            'MAHASISWA KERJA PRAKTEK',
            'MANDIRI AGEN',
            'TUKANG BANGUNAN',
            'TUKANG KEBUN/POTONG RUMPUT',
            'PETUGAS KEBERSIHAN',
            'PENENUN',
            'PENGRAJIN',
            'PANDAI BESI',
            'PANDITA/PEMANGKU',
            'AGEN POS',
            'RELAWAN BAZNAS',
            'DAILY WORKER HOTEL',
            'TUKANG CUCI',
            'PEMASAR',
            'OJEK PANGKALAN',
            'MITRA LALAMOVE',
            'MITRA INDRIVER',
            'KURIR',
            'PENATUA',
            'AGEN BJB LAKU PANDAI',
            'O-RANGER POS INDONESIA',
            'PEMANDU WISATA',
            'PEMILIK USAHA',
            'PEKERJA MANDIRI PNM',
            'PEKERJA DIGITAL',
            'SURVEYOR',
            'RELAWAN TOKOH',
            'PELAYAN GEREJA',
            'PRAMUGOLF',
            'PENAMBANG RAKYAT',
            'KURIR SHOPEE',
            'MITRA MAXIM',
            'MITRA JOGJAKITA',
            'PETUGAS PEMAKAMAN',
            'MITRA GOJEK',
            'MITRA GRAB',
            'AGEN BSI',
        ];

        foreach ($data as $item) {
            \App\Models\Pekerjaan::firstOrCreate([
                'nama' => $item,
            ]);
        }
    }
}
